spring:
  application:
    name: starshop
  datasource:
    url: jdbc:postgresql://localhost:5432/flower_shop_system
    username: flower_admin
    password: flower_password_2024
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 45091665731-js8rgkgu5c662khuebpcieikh47eps6t.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          facebook:
            client-id: 1220413069770726
            client-secret: c5b7d1d07a1564b8bf592045bafbc144
            scope: email,public_profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
            token-uri: https://graph.facebook.com/v18.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/v18.0/me?fields=id,name,email,picture
            user-name-attribute: id

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Asia/Ho_Chi_Minh
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Mail configuration for Gmail SMTP
  mail:
    host: smtp.gmail.com
    port: 587
    username: starshop.a.6868@gmail.com
    password: mqai nigf sweg imek
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          ssl:
            trust: smtp.gmail.com
    default-encoding: UTF-8
    from: starshop.a.6868@gmail.com

jwt:
  secret: starshop_jwt_secret_key_2024_very_secure_key_for_production_use
  expiration: 86400000 # 24 hours in milliseconds

server:
  port: 8080
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: false
        secure: false
        same-site: lax
        max-age: 3600

logging:
  level:
    root: INFO
    com.example.demo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    display-request-duration: true

momo:
  base-url: https://test-payment.momo.vn
  partner-code: MOMO
  access-key: F8BBA842ECF85
  secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
  return-url: http://localhost:8080/payment/momo/return
  notify-url: ${NGROK_URL:http://localhost:8080}/payment/momo/notify
  request-type: captureWallet
  endpoint-create: /v2/gateway/api/create
  endpoint-query: /v2/gateway/api/query

# Ngrok configuration for development
ngrok:
  api:
    url: http://localhost:4040/api/tunnels
  url:
    file: .ngrok-url

# GHN (Giao Hang Nhanh) Configuration
ghn:
  base-url: https://online-gateway.ghn.vn/shiip/public-api
  token: ${GHN_TOKEN:cd8acb1f-9e9c-11f0-b0e8-f2157cd9069b}
  shop-id: ${GHN_SHOP_ID:6040148}
  service-type-id-default: 2
  from:
    # TODO: Fill these with actual GHN codes for HCMUTE location
    province-id: ${GHN_FROM_PROVINCE_ID:202}   # TPHCM Province ID from GHN
    district-id: ${GHN_FROM_DISTRICT_ID:3695}   # Thu Duc District ID from GHN  
    ward-code: ${GHN_FROM_WARD_CODE:90745}       # Specific Ward Code from GHN
  endpoints:
    provinces: /master-data/province
    districts: /master-data/district
    wards: /master-data/ward
    calculate-fee: /v2/shipping-order/fee
